---
- hosts: deb9
  remote_user: root  
  tasks:
    # install basic tools
    - name: install UFW - Uncomplicated Firewall
      apt: name=ufw state=latest update_cache=yes

    - name: set loging
      ufw: logging=on
    
    - name: enable ufw
      ufw: state=enabled policy=allow
