---
- hosts: deb9
  remote_user: root
  vars_files:
    - ufw-var.yml
  tasks:
    - name: default deny from all
      ufw: default=deny direction=incoming

    - name: allow only ssh from {{ allow_ip }}
      ufw: from_ip={{ allow_ip }} to_port=22 rule=allow

    - name: allow http in from All
      ufw: to_port=80 rule=allow
    
    - name: allow http out from All
      ufw: to_port=80 rule=allow direction=out

    - name: allow https in from All
      ufw: to_port=443 rule=allow
    
    - name: allow https out from All
      ufw: to_port=443 rule=allow  direction=out